// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtwD4iMB86NcAXFoeAX7LeP87L46WEMqY',
    appId: '1:512698976793:web:d056d4585cf41548333888',
    messagingSenderId: '512698976793',
    projectId: 'student-management-app-b610a',
    authDomain: 'student-management-app-b610a.firebaseapp.com',
    storageBucket: 'student-management-app-b610a.firebasestorage.app',
    measurementId: 'G-2Y54V61N16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYh3vWgz1jr2V0P3xcGkVa4iUOziHNghI',
    appId: '1:512698976793:android:793efe46b4860671333888',
    messagingSenderId: '512698976793',
    projectId: 'student-management-app-b610a',
    storageBucket: 'student-management-app-b610a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS8Pa9OirVZrppxEn16RGuP9bwK9v79-w',
    appId: '1:512698976793:ios:f0d06427f0a8220d333888',
    messagingSenderId: '512698976793',
    projectId: 'student-management-app-b610a',
    storageBucket: 'student-management-app-b610a.firebasestorage.app',
    iosBundleId: 'com.example.studentManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS8Pa9OirVZrppxEn16RGuP9bwK9v79-w',
    appId: '1:512698976793:ios:f0d06427f0a8220d333888',
    messagingSenderId: '512698976793',
    projectId: 'student-management-app-b610a',
    storageBucket: 'student-management-app-b610a.firebasestorage.app',
    iosBundleId: 'com.example.studentManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtwD4iMB86NcAXFoeAX7LeP87L46WEMqY',
    appId: '1:512698976793:web:16991631feae2c4f333888',
    messagingSenderId: '512698976793',
    projectId: 'student-management-app-b610a',
    authDomain: 'student-management-app-b610a.firebaseapp.com',
    storageBucket: 'student-management-app-b610a.firebasestorage.app',
    measurementId: 'G-22HJFD8W2Y',
  );
}
