import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Ensure this was generated by flutterfire configure

// Import your neatly organized UI screens
import 'screens/login_screen.dart';
import 'screens/register_screen.dart';
import 'screens/dashboard_screen.dart';

void main() async {
  // 1. Ensure Flutter bindings are ready before interacting with native code
  WidgetsFlutterBinding.ensureInitialized();

  // 2. Initialize the Firebase Engine
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // 3. Launch the Application
  runApp(const MiniStudentApp());
}

class MiniStudentApp extends StatelessWidget {
  const MiniStudentApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Student Manager',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.blueAccent),
        useMaterial3: true,
      ),
      // Set the very first screen the user sees
      initialRoute: '/login',

      // Define the navigation map
      routes: {
        '/login': (context) => const LoginScreen(),
        '/register': (context) => const RegisterScreen(),
        '/dashboard': (context) => DashboardScreen(),
      },
    );
  }
}